### PR TITLE
Add atomics support to DTS JSON file.

### PR DESCRIPTION
**Pull request by richardxia**
cc @mikeyangsiv

This updates the DTS JSON file to include an `A` property if it supports all types of atomics.

### CODE REVIEW

**Comment by solomatnikov** [comment]
I think it makes sense to add LR/SC permission as well b/c some memories/devices support atomics but not LR/SC

**Comment by richardxia** [comment]
I don't know the details of our TileLink implementation. Is there a simple expression for determining whether LR/SC is supported using the info available in `TLManagerParameters`?

**Comment by solomatnikov** [comment]
AFAIK LR/SC are supported if atomics are supported and memory is cacheable but it's really a question for @aswaterman

**Comment by hcook** [comment]
No. Those are handled internally to the L1 Dcache, i.e. before you even get to Diplomacy / Tilelink. I think they're supported for all cacheable address ranges?

**Comment by solomatnikov** [comment]
So, cacheable + atomics is not sufficient for LR/SC. It must be cacheable in L1 DCache.

**Comment by hcook** [comment]
From the perspective of software executing on a processor, what cacheable address ranges are not cacheable in the L1 DCache?

**Comment by solomatnikov** [comment]
The core might have no L1 DCache but it can still access cacheable memory region, which can be cached by other cores that do have L1 DCache.

**Comment by hcook** [comment]
There's a whole other can of worms related to heterogeneous processors that isn't even worth opening here. ATM, we only print out a single address map (from the perspective of the system bus crossbar), so you can't specialize it per tile anyways. I think that's out of scope for this PR.

**Comment by terpstra** [comment]
LR/SC is implied by the cacheability bit

**Comment by aswaterman** [comment]
Yes, it must be cached by the L1, not just cacheable. Specifically, a DTIM can't do LR/SC, even though it might have access to memory marked cacheable.

**Pull request merged**
