### PR TITLE
Debug exception assert 2

### PR DESCRIPTION
**Pull request by mwachs5**
This is the same as #1420 , but for some reason Travis won't start that one. Opening this to attempt to jump-start it.

### CODE REVIEW

**Comment by solomatnikov** [comment]
Does it make sense to add cover for debug exception for the case when it should happen?

**Comment by mwachs5** [comment]
The more covers the better, but not sure exactly what you mean. You mean, the case when we are expecting to get an exception write?

**Comment by solomatnikov** [comment]
I am assuming there are cases when debug exceptions are needed, right? Otherwise, why are they in the design. So, covers for those cases.

**Comment by mwachs5** [comment]
This is not working any better than the previous one in terms of Travis not ignoring it so just going to close this one.

**Pull request closed without merging**
