### PR TITLE
bump riscv-tools

### PR DESCRIPTION
**Pull request by yunsup**

### CODE REVIEW

**Comment by yunsup** [comment]
is there anything special I need to do for riscv-tools caching?

**Comment by palmer-dabbelt** [comment]
I think you need to turn on the build for PRs and then clear the cache?

**Comment by hcook** [comment]
https://github.com/freechipsproject/rocket-chip/blob/master/README_TRAVIS.md

**Comment by yunsup** [comment]
thanks @hcook

**Comment by aswaterman** [comment]
I'm looking into the failure

**Pull request merged**
