### PR TITLE
Bus blocker lock

### PR DESCRIPTION
**Pull request by terpstra**
d'oh!

### CODE REVIEW

**Comment by aswaterman** [comment]
So just to confirm the functionality:

- pmp(i).l locks pmp(i).everything
- pmp(i+1).l locks only pmp(i).address

**Comment by terpstra** [comment]
Err. I had pmp(i+1).l locking everything of pmp(i). What is the intended behaviour?

**Comment by terpstra** [comment]
Ok. I've pushed a version that only protects the PRIO address if l AND a are true.

**Comment by terpstra** [comment]
Done.

**Pull request merged**
