### PR TITLE
Fix AsyncResetReg

### PR DESCRIPTION
**Pull request by rmac-sifive**
This fixes a reset race condition caused when the reset of an AsyncResetReg_1 is driven by another AsyncResetReg_2. In that case, the AsyncResetReg_2's initialization behavior could cause AsyncResetReg_1 to be undefined

### CODE REVIEW

**Comment by aswaterman** [comment]
I'm leery of the removal of the 0.002 delay - why's that OK here?

**Comment by rmac-sifive** [comment]
This fixed an issue I see in simulation in which the reset of AsyncResetReg_1 was driven from AsyncResetReg_2. In that case, the assignments at t=0.002 raced, and AsyncResetReg_1's intial block at t=0.002 executed first, rst was not defined, and AsyncResetReg_1 starts simulation undefined

Now that I think of it, I think this PR only moves the same race to t=0, and it works by chance, since if AsyncResetReg_1's t=0 initial block executes first we'll have the same issue

Would just assigning q = _RAND at t=0.002 as we do with other registers work? Why do we ever need registers to have their reset value at t=0.002? I would expect some external reset should propagate through the design to do this

**Comment by rmac-sifive** [comment]
@aswaterman, @jackkoenig, I've updated the PR to get rid of the initialization based on `rst` as we discussed offline. Now this unit is only initialized to `_RAND`, which is consistent with methodology for other registers

This fixed the issue I was seeing, but I will run a few more test cases before merging

**Comment by rmac-sifive** [comment]
After running into issues with the previous version, it became apparent that the DMOuter domain (clocked externally by JTAG, SimJTAG in simulation), was relying on AsyncResetReg's previous behavior which initialization flops to their reset value at t = 0. This was masking the bug that the DMOuter clock domain was not reset properly, because TCK was never toggled during reset

**Pull request merged**
