### PR TITLE
Add a clock divider with explicit input clock

### PR DESCRIPTION
**Pull request by rmac-sifive**
Adds a clock divider module which allows for an explicit clock input, and rewrites `Pow2ClockDivider` to instantiate this module for legacy compatibility

### CODE REVIEW

**Comment by aswaterman** [comment]
@hcook should make the call, but another option is making a companion object, and for the explicit version, use withClock as the means to pass it in:

    object Pow2ClockDivider {
      // legacy version
      def apply(pow2: Int): Clock = Module(new Pow2ClockDivider(pow2)).clock_out

      // new version
      def apply(clock_in: Clock, pow2: Int): Clock = withClock(clock_in) { apply(pow2) }
    }

**Comment by rmac-sifive** [comment]
@aswaterman with that solution, I think I'd have to modify the each instantiation of the divider in the code-base from `Module(new Pow2ClockDivider(n))` to just`Pow2ClockDivider`, right?

**Comment by aswaterman** [comment]
I'm proposing keeping the existing module entirely as-is, so old code doesn't have to change (but new code should probably favor `Pow2ClockDivider(n)`)

**Comment by rmac-sifive** [comment]
Ah, understood. I'll leave it to @hcook which implementation to take

**Comment by rmac-sifive** [comment]
I talked to Henry offline and he prefers the object implementation, and I updated the PR to that implementation

**Pull request merged**
