### PR TITLE
test to add buffering to tile

### PR DESCRIPTION
**Pull request by yunsup**

### CODE REVIEW

**Comment by yunsup** [comment]
Don't merge this branch.  I'm going to make the buffering optional.  I'll follow up with a different PR.

**Comment by hcook** [comment]
When making the buffering optional, consider whether this is something that should apply to the other types of tile crossings as well. I'm not sure whether it should be associated with `CoreplexCrossing` or `RocketTileParams`, but am leaning towards the latter because the former is used in more places

**Comment by terpstra** [comment]
It does NOT apply to an async crossing.

I think it does apply to rational an synchronous connections.

**Comment by yunsup** [comment]
@terpstra that is correct.  @hcook I wanted to put the option as part of the RocketTileParams, and only put the buffering in rational and synchronous rocket tiles.  I'm going to close this PR, and make another one soon.  Thanks everyone.

**Comment by yunsup** [comment]
now #909

**Pull request closed without merging**
