### PR TITLE
Generalize CSR file to support simpler cores

### PR DESCRIPTION
**Pull request by aswaterman**

### CODE REVIEW

**Comment by hcook** [comment]
the `HasRocketCoreParameters` to `HasCoreParameters` stuff lgtm

**Comment by hcook** [comment]
Any further thoughts on https://github.com/freechipsproject/rocket-chip/issues/733?

**Comment by aswaterman** [comment]
Not yet; it might just be that #733 demands another field in ```HasCoreParameters```.  Note, it doesn't demand another argument to ```RocketCoreParameters```, since there you can just ```def maxPerfCounterIncrement = retireWidth``` or whatever.

**Comment by aswaterman** [comment]
With that in mind, now that cross-module width inference is reliable, maybe we don't need a parameter at all.  There are a few details to get right if we go that route (e.g., WideCounter is optimized for the case that the increment is 1 bit, and that savings would be lost).

**Comment by aswaterman** [comment]
Actually, since CSRFile has the perfEvents, there's no need to rely on inference - perfEvents should specify each width somehow.

**Comment by ccelio** [comment]
On the topic of CSRFiles and the removal of the custom CSRs, have you guys considered how to support "chicken bits"? 

For example, I have a memory disambiguator predictor that clears all of the entries every N cycles. I would like N to be set by a CSR, and where N==0 disables the predictor.

**Comment by aswaterman** [comment]
I prefer not to add these as CSRs,
because that address space is more limited, not indexable, messy to
assemble for, etc. I've recently added a tile control port (an MMIO device)
that is currently only used to report ECC/bus errors. It could also be used
to hold nonstandard configuration registers.

**Pull request merged**
