### PR TITLE
Clock-gate the debug module using the dmactive signal

### PR DESCRIPTION
**Pull request by aswaterman**
**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

### CODE REVIEW

**Comment by aswaterman** [comment]
@mwachs5 I've updated the PR to once again reset the DM state when dmactive falls.

One note of caution, I've added a config option to engage DM clock gating, but I've defaulted it to on.  I think that's what we want in general, just keep in mind if trying to be conservative.

**Comment by aswaterman** [comment]
Thanks for the feedback; I addressed it.

**Comment by mwachs5** [comment]
See https://github.com/riscv/riscv-debug-spec/issues/395

What happens if DEBUGGER tries to read a debug module register when dmactive=0? It seems that this would not get through the Clock Domain Crossing into the DebugModuleInner, yet, the debug tests are passing in regression... I'm not sure how this is working

**Comment by aswaterman** [comment]
Because we are still clocking the DMI crossing.  (Whether we should be doing that is up for debate.)

**Pull request merged**
