### PR TITLE
adding BusError LTN and OM

### PR DESCRIPTION
**Pull request by derekpappas**
**Related issue**: 

**Type of change**: feature request

**Impact**: API addition (no impact on existing code

**Development Phase**: implementation

**Release Notes**

Adding the BusErrorUnit LogicalTreenNode and the Object Model

### CODE REVIEW

**Comment by derekpappas** [comment]
Who owns the bus encoder unit?

**Comment by aswaterman** [comment]
I do, but I'm in transit so can't give this a good review; hopefully someone else can.

**Comment by derekpappas** [comment]
Yes this PR just adds the GEU to the logical tree.

**Comment by hcook** [comment]
In the closed-source tiles, you made each tile have its own logical tree node. Why are you treating rocket differently?

**Comment by derekpappas** [comment]
I don't understand your comment.

Can you point to line numbers that are a problem?

**Pull request merged**
